version: "2"
services:
  file_storage_mongo_db:
    image: mongo
    ports:
      - "27017:27017"
  usermanagement_mongo_db:
    image: mongo
    ports:
      - "27018:27017"
  liabilities_mongo_db:
    image: mongo
    ports:
      - "27019:27017"
  file_storage_redis:
    image: redis
    ports:
      - "6379:6379"
  file_storage:
    build: file_storage
    ports:
      - "8000:8000"
    volumes:
      - "./file_storage:/file_storage"
    links:
      - file_storage_mongo_db
      - file_storage_redis
    depends_on:
      - file_storage_mongo_db
      - file_storage_redis
    environment:
      - MONGODB_URL=file_storage_mongo_db
      - MONGODB_PORT=27017
      - REDIS_URL=file_storage_redis
      - REDIS_PORT=6379
      - PORT=8000
  liabilities:
      build: liabilities
      ports:
        - "8001:8001"
      volumes:
        - "./liabilities:/liabilities"
      links:
        - liabilities_mongo_db
        - file_storage
      depends_on:
        - liabilities_mongo_db
      environment:
        - MONGODB_URL=liabilities_mongo_db
        - MONGODB_PORT=27019
        - PORT=8001
  usermanagement:
    build: usermanagement
    ports:
      - "8002:8002"
    volumes:
      - "./usermanagement:/usermanagement"
    links:
      - usermanagement_mongo_db
    depends_on:
      - usermanagement_mongo_db
    environment:
      - MONGODB_URL=liability_mongo_db
      - MONGODB_PORT=27018
      - PORT=8002
  webapp:
    build: webapp
    ports:
      - "3000:3000"
    volumes:
      - "./webapp:/webapp"
    links:
      - file_storage
      - usermanagement
      - liabilities
