version: "2"
services:
  file_storage_mongo_db:
    image: mongo
    ports:
      - "27017:27017"
  usermanagement_mongo_db:
    image: mongo
    ports:
      - "27018:27017"
  liability_mongo_db:
    image: mongo
    ports:
      - "27019:27017"
  file_storage_redis:
    image: redis
    ports:
      - "6379:6379"
  file_storage:
    build: file_storage
    ports:
      - "8000:8000"
    volumes:
      - "./file_storage:/file_storage"
    links:
      - file_storage_mongo_db
      - file_storage_redis
    depends_on:
      - file_storage_mongo_db
      - file_storage_redis
    environment:
      - MONGODB_URL=file_storage_mongo_db
      - MONGODB_PORT=27017
  usermanagement:
    build: usermanagement
    ports:
      - "8001:8000"
    volumes:
      - "./usermanagement:/usermanagement"
    links:
      - usermanagement_mongo_db
    depends_on:
      - usermanagement_mongo_db
    environment:
      - MONGODB_URL=file_storage_mongo_db
      - MONGODB_PORT=27018
  webapp:
    build: webapp
    ports:
      - "3000:3000"
    volumes:
      - "./webapp:/webapp"
    links:
      - file_storage
